### ISSUE TITLE
MariaDB

### ISSUE THREAD

**Issue by cfouche3005** [parkervcp/yolks#44] opened 2022-02-22 22:48 UTC
Hi, I have seen that mariadb images have been added but they doesn't work with https://github.com/parkervcp/eggs/blob/master/database/sql/mariadb/egg-maria-d-b.json
and don't know what change is needed to make it work.
Thank for all the future help.

**Comment by Davinel17** [comment] 2022-08-31 21:22
error during installation 


installing mysql database
+ runuser -l container -c 'mkdir -p /mnt/server/run/mysqld'
+ runuser -l container -c 'mkdir -p /mnt/server/log/mysql'
+ runuser -l container -c 'mkdir /mnt/server/mysql'
mkdir: cannot create directory '/mnt/server/mysql': File exists
+ runuser -l container -c 'mysql_install_db --defaults-file=/mnt/server/.my.cnf'
Installing MariaDB/MySQL system tables in '/mnt/server/mysql' ...
2022-08-31 21:20:15 0 [Warning] Can't create test file /mnt/server/mysql/installer.lower-test
2022-08-31 21:20:15 0 [ERROR] mariadbd: Can't create/write to file './ddl_recovery.log' (Errcode: 13 "Permission denied")
2022-08-31 21:20:15 0 [ERROR] DDL_LOG: Failed to create ddl log file: ./ddl_recovery.log
2022-08-31 21:20:15 0 [ERROR] Aborting
Installation of system tables failed!  Examine the logs in
/mnt/server/mysql for more information.
The problem could be conflicting information in an external
my.cnf files. You can ignore these by doing:
    shell> /usr/bin/mysql_install_db --defaults-file=~/.my.cnf
You can also try to start the mysqld daemon with:
    shell> /usr/sbin/mariadbd --skip-grant-tables --general-log &
and use the command line tool /usr/bin/mariadb
to connect to the mysql database and look at the grant tables:
    shell> /usr/bin/mysql -u root mysql
    mysql> show tables;
Try 'mysqld --help' if you have problems with paths.  Using
--general-log gives you a log in /mnt/server/mysql that may be helpful.
The latest information about mysql_install_db is available at
https://mariadb.com/kb/en/installing-system-tables-mysql_install_db
You can find the latest source at https://downloads.mariadb.org and
the maria-discuss email list at https://launchpad.net/~maria-discuss
Please check all of the above before submitting a bug report
at https://mariadb.org/jira
+ '[' -f /mnt/server/custom.my.cnf ']'
+ echo -e 'moving current config back in place'
moving current config back in place
+ mv /mnt/server/custom.my.cnf /mnt/server/.my.cnf
+ echo -e 'install complete'
install complete
+ exit

**Comment by parkervcp** [comment] 2022-08-31 22:40
the problem is that the install script uses one version of mariadb and the run image is separate. So we really need to just have different eggs for different versions. I am going to close this and we can talk on the egg issue.

**Closed by parkervcp** 2022-08-31 22:40 UTC
